repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        pass_filenames: true
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        pass_filenames: true
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check .
        pass_filenames: false
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        pass_filenames: false
        language: system
        types:
          - python
